function f = right_f_de (ro, x_v)
x_v = x_v';
V = x_v(1);
M = x_v(2);
R = 6371 * 1e5;
theta = x_v(3);
delta = 3.5;
c_d = 1;
f = 1.21;
K = @(theta) f*c_d/(2*delta^(2/3)*sin(theta));
h = h_interpolate(ro);
q = K(theta);
z = z_interpolate(ro);
%sigma = sigma_interpolate(V);
sigma = 1e-12;
g = g_i(ro);
y_1 = -K(theta)*h*V/M^(1/3) + g*h/(ro*V);
y_2 = -K(theta)*h*sigma*V^2*real(M^(2))^(1/3);
y_3 = g*h*cot(theta)*(g/V - V/(R + z))/(ro*V^2);
f = [real(y_1),real(y_2), y_3]';
end